Project: Library app
Anna-Myzukina/library pull request #2
Opened 2020-04-08 09:53 UTC by Anna-Myzukina

We created a small Library app.
You can add a new book.
Our book objects have:
- the book’s title, 
- author, 
- the number of pages, 
- and whether or not you have read the book

Please review our project!

2020-04-08 20:16 UTC, maelfosso requested changes
# Changes required :red_circle:

Hello coders,
Your project is OK. However, there is a requirement you forgot.
According to [that](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/new_book_button_requirement.png), you should make the form appear after clicking on `Add Book` button.

- Please, remove the `console.log` instructions.

- Also, please read the comment below.

Kindly make the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

2020-04-08 20:16 UTC, maelfosso commented on app.js
> +}
Please, make this code lisible by indenting it.

2020-04-08 20:16 UTC, maelfosso commented on app.js
> +    alert("Local Storage will be used");
That is not needed, please remove it.

2020-04-27 15:09 UTC, emmanuelkamala commented
1. I have added functionality whereby when a user clicks the 'New Book', then the form appears, so the form shows when a user clicks the 'New Book' button

2. I have removed all areas that had console.log in the app

2020-04-27 16:15 UTC, jofer86 approved these changes
## :wave: :wave: Hello!, I'm Jorge, and  I'm here to review this Pull Request, let's take a look shall we :eye: :eye: :eye: 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- From what I can see, you have tackled all of the required changes asked by the previous reviewer!!!. This project is now complete. Great Job!!!
--------------------------------------------------------------------
Cheers, 
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-04-27 17:08 UTC, merged